apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxljob-admin
  namespace: bsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxljob-admin
  template:
    metadata:
      annotations:
      labels:
        app: xxljob-admin
    spec:
      containers:
        - image: xuxueli/xxl-job-admin:2.4.0
          name: xxljob-admin
          resources:
            limits:
              memory: 2048Mi
              cpu: 2
            requests:
              memory: 2048Mi
              cpu: 2
          env:
           - name: PARAMS
             value: "--spring.datasource.url=jdbc:mysql://your.db:3306/xxljob?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=yourpassword --xxl.job.accessToken=youraccesstoken"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxljob-admin
  name: xxljob-admin
  namespace: bsa
spec:
  ports:
    - name: tcp8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: xxljob-admin
  type: ClusterIP